// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotiFIITBot.Database.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotiFIITBot.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    partial class ScheduleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotiFIITBot.Database.Models.LessonModel", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("AuditoryLocation")
                        .HasColumnType("text")
                        .HasColumnName("classroom_route_url");

                    b.Property<string>("ClassroomNumber")
                        .HasColumnType("text")
                        .HasColumnName("classroom_number");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("Evenness")
                        .HasColumnType("integer")
                        .HasColumnName("evenness");

                    b.Property<int>("MenGroup")
                        .HasColumnType("integer")
                        .HasColumnName("men_group");

                    b.Property<int>("PairNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pair_number");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int?>("SubGroup")
                        .HasColumnType("integer")
                        .HasColumnName("sub_group");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject_name");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("teacher_name");

                    b.HasKey("LessonId");

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("NotiFIITBot.Database.Models.User", b =>
                {
                    b.Property<long>("TelegramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelegramId"));

                    b.Property<int>("GlobalNotificationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("global_notification_minutes");

                    b.Property<int>("MenGroup")
                        .HasColumnType("integer")
                        .HasColumnName("men_group");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_enabled");

                    b.Property<int?>("SubGroup")
                        .HasColumnType("integer")
                        .HasColumnName("sub_group");

                    b.HasKey("TelegramId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("NotiFIITBot.Database.Models.UserNotificationConfig", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<bool?>("IsNotificationEnabledOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_notification_enabled_override");

                    b.Property<int?>("NotificationMinutesOverride")
                        .HasColumnType("integer")
                        .HasColumnName("notification_minutes_override");

                    b.HasKey("TelegramId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("user_notification_config");
                });

            modelBuilder.Entity("NotiFIITBot.Database.Models.WeekEvennessConfig", b =>
                {
                    b.Property<int>("Evenness")
                        .HasColumnType("integer")
                        .HasColumnName("evenness");

                    b.Property<DateOnly>("FirstMonday")
                        .HasColumnType("date")
                        .HasColumnName("first_monday");

                    b.HasKey("Evenness");

                    b.ToTable("week_evenness_configs");
                });

            modelBuilder.Entity("NotiFIITBot.Database.Models.UserNotificationConfig", b =>
                {
                    b.HasOne("NotiFIITBot.Database.Models.LessonModel", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotiFIITBot.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("TelegramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
