// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotiFIITBot.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotiFIITBot.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    partial class ScheduleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "evenness", new[] { "even", "odd", "always" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lesson_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<int?>("ClassroomNumber")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_number");

                    b.Property<string>("ClassroomRoute")
                        .HasColumnType("text")
                        .HasColumnName("classroom_route_url");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("PairNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pair_number");

                    b.Property<int>("Parity")
                        .HasColumnType("integer")
                        .HasColumnName("parity");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject_name");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("teacher_name");

                    b.HasKey("LessonId");

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("NotiFIITBot.Models.User", b =>
                {
                    b.Property<long>("TelegramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelegramId"));

                    b.Property<int>("GlobalNotificationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("global_notification_minutes");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("integer")
                        .HasColumnName("group_number");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_enabled");

                    b.Property<int?>("SubGroupNumber")
                        .HasColumnType("integer")
                        .HasColumnName("subgroup_number");

                    b.HasKey("TelegramId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("NotiFIITBot.Models.UserNotificationConfig", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_id");

                    b.Property<bool?>("IsNotificationEnabledOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_notification_enabled_override");

                    b.Property<int?>("NotificationMinutesOverride")
                        .HasColumnType("integer")
                        .HasColumnName("notification_minutes_override");

                    b.HasKey("TelegramId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("user_notification_config");
                });

            modelBuilder.Entity("NotiFIITBot.Models.WeekParityConfig", b =>
                {
                    b.Property<int>("Parity")
                        .HasColumnType("integer")
                        .HasColumnName("parity");

                    b.Property<DateOnly>("FirstMonday")
                        .HasColumnType("date")
                        .HasColumnName("first_monday");

                    b.HasKey("Parity");

                    b.ToTable("week_parity_configs");
                });

            modelBuilder.Entity("NotiFIITBot.Models.UserNotificationConfig", b =>
                {
                    b.HasOne("Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotiFIITBot.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("TelegramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
